Projecten 2/Website/BreakOutBox/Models/Beheer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BreakOutBox.Models
{
    public class Beheer
    {
    }
}

Projecten 2/Website/BreakOutBox/Controllers/BeheerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BreakOutBox.Models;
using Microsoft.AspNetCore.Mvc;
using BreakOutBox.Filters;
using BreakOutBox.Models.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;

namespace BreakOutBox.Controllers
{
    [Authorize]
    [ServiceFilter(typeof(SessieFilter))]
    public class BeheerController : Controller
    {
        public string sessieCode { get; set; }
        private readonly ISessieRepository sessieRepository;
        private readonly IVooruitgangRepository vooruitgangRepository;
        private readonly IBoxRepository boxRepository;


        public BeheerController(ISessieRepository sessieRepository, IVooruitgangRepository vooruitgangRepository, IBoxRepository boxRepository)
        {
            this.sessieRepository = sessieRepository;
            this.vooruitgangRepository = vooruitgangRepository;
            this.boxRepository = boxRepository;
        }

        public ActionResult Index()
        {
            IEnumerable<Sessie> _sessies = this.sessieRepository.GetAll();
            return View(_sessies);
        }

        [HttpPost]
        public ActionResult Index(Sessie sessie, string sessiecode)
        {
            Sessie sessieObj = this.sessieRepository.getByCode(sessiecode);
            if (sessieObj != null)
            {
                sessie.Omschrijving = sessieObj.Omschrijving;
                sessie.Afstandsonderwijs = sessieObj.Afstandsonderwijs;
                sessie.Beschikbaarvanaf = sessieObj.Beschikbaarvanaf;
                sessie.BoxNaam = sessieObj.BoxNaam;
                sessie.BoxNaamNavigation = sessieObj.BoxNaamNavigation;
                sessie.Code = sessieObj.Code;
                sessie.Naam = sessieObj.Naam;
                sessie.SessieGroep = sessieObj.SessieGroep;
                
                return RedirectToAction(nameof(Groepsoverzicht));
            }
            return RedirectToAction(nameof(Index));

        }

        public ActionResult Groepsoverzicht(Sessie sessie)
        {
            var aantalOefeningen = boxRepository.getOefeningenByBox(sessie.BoxNaam).Count();
            TempData["aantalOefeningen"] = aantalOefeningen;
            IEnumerable<Vooruitgang> vooruitgangen = this.vooruitgangRepository.GetVooruitgangenBySessieNaam(sessie.Naam);
            return View(vooruitgangen);
        }

        [HttpPost]
        public ActionResult Groepsoverzicht(string id)
        {
            var vooruit = vooruitgangRepository.GetBy(id);
            var sessienaam = vooruit.Sessienaam;
            var oefnummer = vooruit.OefNummer;
            var score = vooruit.Score;
            var frozen = vooruit.IsFrozen;
            var aantalfoutepog = 0;

            vooruitgangRepository.remove(vooruit);
            vooruitgangRepository.add(new Vooruitgang(sessienaam, id, oefnummer, score, (frozen+3)%2, aantalfoutepog));

            return RedirectToAction(nameof(Groepsoverzicht));
        }

        public ActionResult Refresh()
        {
            return RedirectToAction(nameof(Groepsoverzicht));
        }

        public ActionResult ChangeAllFreezeStatus(string sessiecode, Boolean freeze)
        {
            String sessienaam = this.sessieRepository.GetSessieNaamByCode(sessiecode);
            this.vooruitgangRepository.ChangeAllFrozenBySessieCode(sessienaam, freeze);
            return RedirectToAction(nameof(Index));
        }
    }
}

Projecten 2/Website/BreakOutBox/Views/Beheer/GroepsOverzicht.cshtml
@model IEnumerable<BreakOutBox.Models.Vooruitgang>

<h1>Vooruitgangen</h1>
<hr />

<section>
    <div class="container">
        <div class="row">
            <a asp-action="Refresh" asp-controller="Beheer" method="get" class="btn btn-primary" style="margin-bottom : 10px">Refresh</a>

            @foreach (var item in Model)
            {
                <div class="col-md-3 col-sm-6 card" style="border: 1px solid gray; border-radius: 2px ;margin: 20px; height: 200px;">
                    <div class="card-body">
                        <h4 class="card-title">Groep @item.GroepID</h4>
                        <hr>
                        <p class="card-text">Aantal opgeloste oefeningen: @item.Score van de @TempData["aantalOefeningen"]</p>
                        @{
                            if (item.IsFrozen == 0)
                            {
                                <p class="card-text">Status: niet bevroren</p>

                            }
                            else
                            {
                                <p class="card-text">Status: bevroren</p>

                            }
                        }
                        <form asp-action="GroepsOverzicht" asp-controller="Beheer" asp-route-id=@item.GroepID method="post">
                            <button class="btn btn-primary">Bevries/ Ontvries</button>
                        </form>
                    </div>

                </div>
            }
        </div>
    </div>
</section>

Projecten 2/Website/BreakOutBox/Views/Beheer/Index.cshtml
@model IEnumerable<BreakOutBox.Models.Sessie>

<h2 style="margin-top:3%" class="text-center"> Welkom in het beheerscherm.</h2>
<br />

<section>
    <div class="container">
        <div class="row">
            <a asp-action="Index" asp-controller="Beheer" method="get" class="btn btn-primary" style="float:right;margin-bottom : 10px">Refresh</a>

            <ul>
                @foreach (var item in Model)
                {
                    <li>
                        <div style="margin: 20px; height: 200px;">
                           
                                <h2 class="card-title"> @item.Naam</h2>
                                <h4> Boxnaam: @item.BoxNaam</h4>
                                <h4> Sessiecode: @item.Code</h4>
                                <hr>
                                <div class="row">
                                    <div style="margin:3px" class="col-12 col-md-2">
                                        <form asp-action="Index" asp-controller="Beheer" asp-route-sessiecode=@item.Code method="post">
                                            <button class="btn btn-primary">Details</button>
                                        </form>
                                    </div>
                                    <div style="margin:3px" class="col-12 col-md-2">
                                        <form asp-action="ChangeAllFreezeStatus" asp-controller="Beheer" asp-route-sessiecode=@item.Code asp-route-freeze="true" method="post">
                                            <button class="btn btn-primary">Bevries alle groepen</button>
                                        </form>
                                    </div>
                                    <div style="margin:3px" class="col-12 col-md-2">
                                        <form asp-action="ChangeAllFreezeStatus" asp-controller="Beheer" asp-route-sessiecode=@item.Code asp-route-freeze="false" method="post">
                                            <button class="btn btn-primary">Ontvries alle groepen</button>
                                        </form>
                                    </div>
                                </div>
                            

                        </div>
                        <hr style="color:black" />
                    </li>
                }
            </ul>
        </div>
    </div>
</section>