Projecten 2/Website/BreakOutBox/Models/Sessie.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BreakOutBox.Models
{
    public partial class Sessie
    {
        public Sessie()
        {
            SessieGroep = new HashSet<SessieGroep>();
        }

        [Key]
        public string Naam { get; set; }
        public bool? Afstandsonderwijs { get; set; }
        public string Beschikbaarvanaf { get; set; }
        public string Code { get; set; }
        public string Omschrijving { get; set; }
        public string BoxNaam { get; set; }

        public Box BoxNaamNavigation { get; set; }
        public ICollection<SessieGroep> SessieGroep { get; set; }
    }
}

Projecten 2/Website/BreakOutBox/Controllers/SessieController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using BreakOutBox.Models;
using BreakOutBox.Models.ViewModels;
using BreakOutBox.Filters;
using System.Collections.Generic;
using BreakOutBox.Data.Repositories;
using System.Linq;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Mvc.Filters;
using System.Threading.Tasks;
using dotnet_g05.Data;
using System;
using System.Text.RegularExpressions;

namespace BreakOutBox.Controllers
{
    [ServiceFilter(typeof(SessieFilter))]
    [ServiceFilter(typeof(GroepFilter))]
    public class SessieController : Controller
    {
        private readonly ISessieRepository _sessieRepository;
        private readonly IGroepRepository _groepRepository;
        private readonly IVooruitgangRepository _vooruitgangRepository;
        private readonly IBoxRepository _boxRepository;
        private IEnumerable<Sessie> sessies;
        private IEnumerable<Groep> groepen;
        private string sessieCode;

        public SessieController(ISessieRepository sessieRepository, IGroepRepository groepRepository, IVooruitgangRepository vooruitgangRepository, IBoxRepository boxRepository)
        {
            this._groepRepository = groepRepository;
            this._sessieRepository = sessieRepository;
            this._vooruitgangRepository = vooruitgangRepository;
            this._boxRepository = boxRepository;
            this.sessies = sessieRepository.GetAll().ToList();
            this.groepen = groepRepository.GetAll().ToList();
            
            vooruitgangRepository.saveChanges();

        }
        
        public ActionResult Index()
        {
            SessieIndexViewModel sessieModel = new SessieIndexViewModel();
            return View(sessieModel);
        }

        [HttpPost]
        public ActionResult Index(Sessie sessie, SessieIndexViewModel sessieIndexViewModel)
        {
            this.sessieCode = sessieIndexViewModel.Code;
            var sessieObj = _sessieRepository.GetBy(sessieCode);
            
            string[] beschikbaarVanaf = Regex.Split(sessieObj.Beschikbaarvanaf, " ");
            
            string beschikbaar;
            beschikbaar = beschikbaarVanaf[0] + "/";
            if(beschikbaarVanaf[1].Length == 1)
            {
                beschikbaar += 0;
            }
            beschikbaar += beschikbaarVanaf[1] + "/" + beschikbaarVanaf[2];

            DateTime datum = DateTime.ParseExact(beschikbaar, "dd/MM/yyyy", null);

            if (sessieObj != null && (datum <= DateTime.Now)) 
            {
                
                sessie.Omschrijving = sessieObj.Omschrijving;
                sessie.Afstandsonderwijs = sessieObj.Afstandsonderwijs;
                sessie.Beschikbaarvanaf = sessieObj.Beschikbaarvanaf;
                sessie.BoxNaam = sessieObj.BoxNaam;
                sessie.BoxNaamNavigation = sessieObj.BoxNaamNavigation;
                sessie.Code = sessieObj.Code;
                sessie.Naam = sessieObj.Naam;
                sessie.SessieGroep = sessieObj.SessieGroep;

                return RedirectToAction(nameof(SelectGroup));
                    
            }
            return RedirectToAction(nameof(NietBeschikbaar));
        }

        public ActionResult NietBeschikbaar()
        {
            return View();
        }

        public ActionResult SelectGroup(Sessie sessie)
        {
            var groepen = _sessieRepository.GetGroepenBySessie(sessie.Naam);
            return View(groepen);
        }

        [ServiceFilter(typeof(GroepFilter))]
        public ActionResult StartOefeningen(Sessie sessie, Groep groep, string id)
        {

            string groepid = id;
            System.Diagnostics.Debug.WriteLine(id);
            var groepObj = _groepRepository.GetBy(id);

            groep.Groepnummer = groepObj.Groepnummer;
            groep.GroepOef = groepObj.GroepOef;
            groep.Id = groepObj.Id;
            groep.Leerlingen = groepObj.Leerlingen;
            groep.Mergeall = groepObj.Mergeall;
            groep.SessieGroep = groepObj.SessieGroep;

            var vooruitgang = _vooruitgangRepository.GetBy(id);
            if (vooruitgang != null)
            {
                if (vooruitgang.IsFrozen == 1)
                {
                    return RedirectToAction("FrozenView", "Oefening");
                }

                int aantaloefeningen = _boxRepository.getOefeningenByBox(sessie.BoxNaam).Count();

                string iddienaaroefcontrollerwordtgestuurd = groep.Id;

                if (vooruitgang.OefNummer == aantaloefeningen)
                {

                    return RedirectToAction(nameof(Errorweergave));
                }
            }
            else
            {
                Vooruitgang v = new Vooruitgang(sessie.Naam, groep.Id, 0, 0, 1, 0);
                _vooruitgangRepository.add(v);
                _vooruitgangRepository.saveChanges();

                if (v.IsFrozen == 1)
                {
                    return RedirectToAction("FrozenView", "Oefening");
                }
            } 
                    return RedirectToAction("Index", "Oefening");
        }

        public ActionResult Errorweergave()
        {
            return View();
        }
    }
}

Projecten 2/Website/BreakOutBox/Views/Sessie/Errorweergave.cshtml
@{
    ViewData["Title"] = "Errorweergave";
}

<h2>Deze groep heeft al alle oefeningen opgelost.</h2>

<a asp-action="SelectGroup" asp-controller="Sessie" method="get" class="btn btn-primary" style="margin-bottom : 10px">Ga terug naar groepen.</a>

Projecten 2/Website/BreakOutBox/Views/Sessie/Index.cshtml
@model BreakOutBox.Models.ViewModels.SessieIndexViewModel

    <h2 style="margin-top:3%" class="text-center">Welkom bij Breakoutbox!</h2>
    <br />


    <div class="jumbotron" style=" margin-top:3%">
        <form class="text-center" asp-action="Index" asp-controller="Sessie" method="post">

            <div class=form-group>
                <br />
                <br />
                <h3>Geef de sessiecode hier in om te beginnen: </h3>
                <br />
                <input style="width:70%; margin-top:10px" asp-for="Code" class="form-control center-block" placeholder="">

            </div>

            <div>

                <button style="width:15%; height:10%" class="btn btn-primary" type="submit">Valideer</button>
            </div>
            <br />
            <br />

        </form>
    </div>

Projecten 2/Website/BreakOutBox/Views/Sessie/NietBeschikbaar.cshtml
@{
    ViewData["Title"] = "Sessie nog niet beschikbaar";
}

<h2>Deze sessie is nog niet beschikbaar.</h2>

<a asp-action="Index" asp-controller="Sessie" method="get" class="btn btn-primary" style="margin-bottom : 10px">Ga terug naar sessie.</a>

Projecten 2/Website/BreakOutBox/Views/Sessie/SelectGroup.cshtml
@model IEnumerable<BreakOutBox.Models.Groep>

<h1>Selecteer jouw groep</h1>
<hr />

<section>
    <div class="container">
        @ViewBag.SuccesMessage
        <div class="row">

            @foreach (var item in Model)
       
            {

            <div class="col-md-3 col-sm-6 " style="border: 1px solid gray; border-radius: 5px ;margin: 20px; height: 200px;">
                    <div class="card-body">
                        <h4 class="card-title">Groep @item.Id</h4>
                        <hr>
                        <p class="card-text">@item.Leerlingen</p>
                        <a asp-action="StartOefeningen" asp-controller="Sessie" asp-route-id=@item.Id method="get" class="btn btn-primary" style="position: absolute; bottom: 0;margin-bottom : 10px">Start de oefeningen</a>
                        <!-- <a asp-action="Index" asp-controller="Oefening" method="get" class="btn btn-primary" style="margin-bottom : 10px">start Sessie</a>  -->
                    </div>
            </div>
            }
            
        </div>
    </div>
</section>